import { randomUUID } from 'node:crypto';
export class PostgresStore {
 constructor(url){this.url=url;this.pool=null;this.state=null;this.queue=Promise.resolve()}
 async connect(){let pg;try{pg=await import('pg')}catch{throw new Error('postgres_driver_not_installed')}this.pool=new pg.Pool({connectionString:this.url,ssl:process.env.PGSSL==='disable'?false:{rejectUnauthorized:false}});await this.pool.query(`CREATE TABLE IF NOT EXISTS app_state (id text PRIMARY KEY, revision bigint NOT NULL DEFAULT 0, payload jsonb NOT NULL, updated_at timestamptz NOT NULL DEFAULT now()); CREATE TABLE IF NOT EXISTS schema_migrations (version text PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());`)}
 async load(seed){await this.connect();const client=await this.pool.connect();try{await client.query('BEGIN');const row=await client.query("SELECT payload FROM app_state WHERE id='primary' FOR UPDATE");if(row.rowCount)this.state=row.rows[0].payload;else{this.state=structuredClone(seed);await client.query("INSERT INTO app_state(id,payload) VALUES('primary',$1::jsonb)",[JSON.stringify(this.state)])}await client.query("INSERT INTO schema_migrations(version) VALUES('001_app_state') ON CONFLICT DO NOTHING");await client.query('COMMIT')}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}return this.state}
 mutate(fn){const run=this.queue.then(async()=>{const client=await this.pool.connect();try{await client.query('BEGIN');const row=await client.query("SELECT payload,revision FROM app_state WHERE id='primary' FOR UPDATE");this.state=row.rows[0].payload;const result=await fn(this.state);await client.query("UPDATE app_state SET payload=$1::jsonb,revision=revision+1,updated_at=now() WHERE id='primary'",[JSON.stringify(this.state)]);await client.query('COMMIT');return result}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}});this.queue=run.catch(()=>{});return run}
 async close(){await this.pool?.end()}
}
export async function migrateJsonIntoPostgres(pgStore,jsonState){if(!jsonState)return{imported:false};return pgStore.mutate(state=>{if(state.prototypeState||state.audit?.length)return{imported:false,reason:'postgres_not_empty'};Object.assign(state,structuredClone(jsonState));state.audit=state.audit||[];state.audit.unshift({id:randomUUID(),at:new Date().toISOString(),actorId:'migration',actorRole:'system',action:'storage.migrated_json_to_postgres',entity:'app:state'});return{imported:true}})}
