const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);const byId=(xs=[])=>new Map(xs.map(x=>[x.id,x]));
const deny=(message)=>{throw Object.assign(new Error(message),{status:403})};
function unchanged(before,after,keys){for(const k of keys)if(!same(before[k],after[k]))deny(`forbidden_prototype_field:${k}`)}
const size=v=>Array.isArray(v)?v.length:(v&&typeof v==='object'?Object.values(v).reduce((n,x)=>n+(Array.isArray(x)?x.length:1),0):0);
function noDeletion(before,after,key){if(key==='chatState')return;if(size(after[key])<size(before[key]))deny(`forbidden_prototype_deletion:${key}`)}
function linkedStudent(state,studentId,personId){const student=(state.students||[]).find(x=>x.id===studentId);return !!student&&(student.titulares||[]).includes(personId)}
function validateRequests(before,after,user,identity){const old=byId(before.requests),next=byId(after.requests);for(const [id,prev] of old){const cur=next.get(id);if(!cur)deny('forbidden_request_deletion');if(same(prev,cur))continue;if(user.role==='parent'){if(!linkedStudent(before,prev.studentId,identity.personId))deny('forbidden_parent_request_family');const allowedStatus=cur.status===prev.status||cur.status==='cancelada';if(!allowedStatus)deny('forbidden_parent_request_change');const immutable=['id','kind','studentId','requestedBy','pickupBy','date','time','reason','channel','pickupPoint','code','createdAt','decidedAt','decidedBy','autoApproved','exitAt','exitBy'];for(const key of immutable)if(!same(prev[key],cur[key]))deny(`forbidden_parent_request_field:${key}`)}else if(user.role==='reception'){if(!['aprobada','rechazada','aceptada',prev.status].includes(cur.status))deny('forbidden_reception_request_change')}else if(user.role==='gate'){if(!(prev.status==='aprobada'&&cur.status==='retirado'))deny('forbidden_gate_request_change')}else if(user.role==='teacher')deny('forbidden_teacher_request_change')}for(const [id,cur] of next)if(!old.has(id)&&user.role==='parent'&&(cur.requestedBy!==identity.personId||!linkedStudent(before,cur.studentId,identity.personId)))deny('forbidden_parent_request_owner')}
function busView(busTrips,ownStudentIds){const copy=structuredClone(busTrips||{});for(const trip of Object.values(copy)){if(trip.boarded)for(const id of ownStudentIds)delete trip.boarded[id];if(Array.isArray(trip.noBus))trip.noBus=trip.noBus.filter(id=>!ownStudentIds.has(id))}return copy}
function validateParentBus(before,after,identity){const own=new Set((before.students||[]).filter(s=>(s.titulares||[]).includes(identity.personId)).map(s=>s.id));if(!same(busView(before.busTrips,own),busView(after.busTrips,own)))deny('forbidden_parent_bus_family');for(const [key,next] of Object.entries(after.busTrips||{})){const prev=(before.busTrips||{})[key];if(!prev){const ids=[...Object.keys(next.boarded||{}),...(next.noBus||[])];if(ids.some(id=>!own.has(id)))deny('forbidden_parent_bus_family');const shell={...next,boarded:{},noBus:[]};if(Object.keys(shell).some(k=>!['boarded','noBus'].includes(k)&&shell[k]!=null))deny('forbidden_parent_bus_trip_create')}}}
export function validatePrototypeMutation(before,after,user){if(!before||user.role==='admin')return true;if(!after||typeof after!=='object')throw Object.assign(new Error('invalid_state'),{status:400});const identity=user.prototypeIdentity||{};unchanged(before,after,['school','settings','routes','levels','staff','permissions','students']);for(const key of ['requests','notifications','chats','chatState','log'])noDeletion(before,after,key);validateRequests(before,after,user,identity);
 if(user.role==='parent'){validateParentBus(before,after,identity);const oldPeople=byId(before.persons);for(const p of after.persons||[])if(oldPeople.has(p.id)&&!same(oldPeople.get(p.id),p))deny('forbidden_person_change');for(const a of after.authorizations||[]){const prev=(before.authorizations||[]).find(x=>x.id===a.id);if(prev&&!same(prev,a)&&prev.createdBy!==identity.personId)deny('forbidden_authorization_change');if(!prev&&a.createdBy!==identity.personId)deny('forbidden_authorization_owner')}}
 if(user.role==='reception')unchanged(before,after,['persons','authorizations','busTrips']);if(user.role==='gate')unchanged(before,after,['persons','busTrips']);if(user.role==='teacher')unchanged(before,after,['persons','authorizations','busTrips']);if(user.role==='monitora')unchanged(before,after,['persons','authorizations']);return true}
